- name: 'Check mandatory variables are defined'
  assert:
    that:
      - mongodb_admin_username is defined
      - mongodb_admin_password is defined
      - elasticsearch_superuser_password is defined
      - disk_encryption_key is defined
      - encrypted_disk_size is defined

- name: Update apt-get
  apt:
    update_cache: yes
    cache_valid_time: 3600
