#
# Configures the user used for provisioning to be the deployment user
# A separate deployment user will be added in 1.4.0
#
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Get the current logged in user
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Add user to Docker group
  user:
    name: '{{ current_user }}'
    groups: docker
    append: yes
