- name: 'Install pip3'
  apt:
    name: python3-pip
    state: present

- name: 'Install jq'
  apt:
    name: jq
    state: present

- name: 'Install pexpect python module for ansible expect commands'
  pip:
    name: python3-pexpect
