- name: 'Install pip3'
  apt:
    name: python3-pip
    state: present

- name: 'Install jq'
  apt:
    name: jq
    state: present

- name: 'Install pexpect python module for ansible expect commands'
  apt:
    name: python-3pexpect
    state: absent
