- name: 'Create acme file for traefik'
  file:
    path: /data/traefik/acme.json
    state: touch
    owner: root
    group: application
    # Owner has rwx, group r, others no permissions
    mode: '0740'

- name: 'Create certs directory for traefik'
  file:
    path: /data/traefik/certs
    state: directory
    mode: '700'
    owner: root
    group: application
    # Owner has rwx, group r, others no permissions
    mode: '0740'