- name: 'Create acme file for traefik'
  file:
    path: /data/traefik/acme.json
    state: touch
    owner: root
    group: application
    # Owner has rw, others no permissions
    mode: '0600'

- name: 'Create certs directory for traefik'
  file:
    path: /data/traefik/certs
    state: directory
    owner: euan
    group: euan
    # Owner has rwx, group r, others no permissions
    mode: '0740'

- name: Create crt file with variable content
  copy:
    dest: "/data/traefik/certs/cert.crt"
    content: |
      {{ssl_crt}}
    owner: euan
    group: euan
  when: ssl_crt is defined and ssl_crt | length > 0

- name: Create key file with variable content
  copy:
    dest: "/data/traefik/certs/cert.key"
    content: |
      {{ssl_key}}
    owner: euan
    group: euan
  when: ssl_key is defined and ssl_key | length > 0