# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: 'ssh-alert'
type: 'frequency'
index: 'kibana-alert-history-default'
is_enabled: true
num_events: 1
realert:
  minutes: 1
terms_size: 50
timeframe:
  minutes: 1
timestamp_field: '@timestamp'
timestamp_type: 'iso'
use_strftime_index: false
# https://github.com/Yelp/elastalert/issues/1260
raw_count_keys: false
alert_subject: '{{HOST}}: Login to {} from {} 🚨'
alert_subject_args:
  - 'kibana.alert.context.__es-query.hits[0]_source.user.name'
  - 'kibana.alert.context.__es-query.hits[0]_source.source.ip'
alert_text: 'Login to https://kibana.{{HOST}} to view the alert.'

filter:
  - query:
      term:
        rule.name.keyword:
          value: 'Succesful SSH login'
alert:
  - 'email'
email: '{{ALERT_EMAIL}}'
from_addr: 'alert@opencrvs.org'
smtp_host: '{{SMTP_HOST}}'
# prettier-ignore
smtp_port: {{SMTP_PORT}}
smtp_ssl: false
smtp_auth_file: '/opt/elastalert/auth.yaml'
