Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.network "private_network", type: "dhcp"

  config.hostsupdater.aliases = [
    "opencrvs.local",
    "login.opencrvs.local",
    "config.opencrvs.local",
    "gateway.opencrvs.local",
    "auth.opencrvs.local",
    "countryconfig.opencrvs.local",
    "register.opencrvs.local"
  ]
  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.net_device = "virtio-net-pci"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo lvextend -L +19.5G /dev/ubuntu-vg/ubuntu-lv
  #   sudo resize2fs /dev/ubuntu-vg/ubuntu-lv
  # SHELL
end




