# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: '3.3'

services:
  gateway:
    environment:
      - NODE_ENV=production

  workflow:
    environment:
      - NODE_ENV=production

  search:
    environment:
      - NODE_ENV=production

  metrics:
    environment:
      - NODE_ENV=production

  auth:
    environment:
      - NODE_ENV=production

  user-mgnt:
    environment:
      - NODE_ENV=production

  notification:
    environment:
      - NODE_ENV=production

  webhooks:
    environment:
      - NODE_ENV=production

  config:
    environment:
      - NODE_ENV=production

  scheduler:
    environment:
      - NODE_ENV=production

  documents:
    environment:
      - NODE_ENV=production

  wg-easy:
    image: weejewel/wg-easy:7
    environment:
      - WG_HOST=vpn.{{hostname}}
      - PASSWORD=${WIREGUARD_ADMIN_PASSWORD}
      - WG_DEFAULT_ADDRESS=10.13.13.x
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_PORT=51822
      - WG_POST_UP=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
    volumes:
      - /data/wireguard:/etc/wireguard
    ports:
      - '51822:51820/udp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.vpn.rule=Host(`vpn.{{hostname}}`)'
        - 'traefik.http.services.vpn.loadbalancer.server.port=51821'
        - 'traefik.http.routers.vpn.tls=true'
        - 'traefik.http.routers.vpn.entrypoints=web,websecure'
        - 'traefik.docker.network=opencrvs_vpn'
        - 'traefik.http.middlewares.vpn.headers.customresponseheaders.Pragma=no-cache'
        - 'traefik.http.middlewares.vpn.headers.customresponseheaders.Cache-control=no-store'
        - 'traefik.http.middlewares.vpn.headers.customresponseheaders.X-Robots-Tag=none'
        - 'traefik.http.middlewares.vpn.headers.stsseconds=31536000'
        - 'traefik.http.middlewares.vpn.headers.stsincludesubdomains=true'
        - 'traefik.http.middlewares.vpn.headers.stspreload=true'
    restart: unless-stopped
    networks:
      - vpn

networks:
  vpn:
    driver: overlay
    attachable: false
