# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors. OpenCRVS and the OpenCRVS
# graphic logo are (registered/a) trademark(s) of Plan International.
version: '3.3'

services:
  gateway:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  workflow:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  search:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  metrics:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  auth:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  user-mgnt:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  notification:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  webhooks:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  config:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  documents:
    environment:
      - QA_ENV=true
      - NODE_ENV=production

  scheduler:
    environment:
    - QA_ENV=true
    - NODE_ENV=production
