# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
version: '3.3'

services:
  logstash:
    deploy:
      replicas: 2

  apm-server:
    deploy:
      replicas: 2

  client:
    deploy:
      replicas: 2

  components:
    deploy:
      replicas: 2

  countryconfig:
    deploy:
      replicas: 2

  login:
    deploy:
      replicas: 2

  auth:
    deploy:
      replicas: 2

  user-mgnt:
    environment:
      - MONGO_URL=mongodb://user-mgnt:${USER_MGNT_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/user-mgnt?replicaSet=rs0

  notification:
    deploy:
      replicas: 2

  gateway:
    deploy:
      replicas: 2

  workflow:
    environment:
      - HEARTH_MONGO_URL=mongodb://hearth:${HEARTH_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/hearth-dev?replicaSet=rs0
    deploy:
      replicas: 2

  search:
    deploy:
      replicas: 2

  webhooks:
    environment:
      - MONGO_URL=mongodb://webhooks:${WEBHOOKS_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/webhooks?replicaSet=rs0
    deploy:
      replicas: 2

  metrics:
    environment:
      - MONGO_URL=mongodb://metrics:${METRICS_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/metrics?replicaSet=rs0
      - HEARTH_MONGO_URL=mongodb://hearth:${HEARTH_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/hearth-dev?replicaSet=rs0
      - DASHBOARD_MONGO_URL=mongodb://performance:${PERFORMANCE_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/performance?replicaSet=rs0

  scheduler:
    environment:
      - OPENHIM_MONGO_URL=mongodb://openhim:${OPENHIM_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/openhim-dev?replicaSet=rs0

  config:
    environment:
      - MONGO_URL=mongodb://config:${CONFIG_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/application-config?replicaSet=rs0
    deploy:
      replicas: 2

  hearth:
    environment:
      - mongodb__url=mongodb://hearth:${HEARTH_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/hearth-dev?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    deploy:
      replicas: 2

  migration:
    environment:
      - USER_MGNT_MONGO_URL=mongodb://user-mgnt:${USER_MGNT_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/user-mgnt?replicaSet=rs0
      - PERFORMANCE_MONGO_URL=mongodb://user-mgnt:${PERFORMANCE_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/performance?replicaSet=rs0
      - APPLICATION_CONFIG_MONGO_URL=mongodb://config:${CONFIG_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/application-config?replicaSet=rs0
      - HEARTH_MONGO_URL=mongodb://hearth:${HEARTH_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/hearth-dev?replicaSet=rs0
      - OPENHIM_MONGO_URL=mongodb://openhim:${OPENHIM_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/openhim-dev?replicaSet=rs0
      - WAIT_HOSTS=mongo1:27017,mongo2:27017,mongo3:27017,mongo4:27017,mongo5:27017,influxdb:8086,minio:9000,elasticsearch:9200
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  openhim-core:
    environment:
      - mongo_url=mongodb://openhim:${OPENHIM_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/openhim-dev?replicaSet=rs0
      - mongo_atnaUrl=mongodb://openhim:${OPENHIM_MONGODB_PASSWORD}@mongo1,mongo2,mongo3,mongo4,mongo5/openhim-dev?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    deploy:
      replicas: 2

  mongo2:
    image: mongo:4.4
    hostname: 'mongo2'
    container_name: 'mongo2'
    restart: unless-stopped
    command: mongod --auth --replSet rs0 --keyFile /etc/mongodb-keyfile
    volumes:
      - '/data/mongo:/data/db'
      - '/mongodb-keyfile:/mongodb-keyfile'
    # https://github.com/docker-library/mongo/issues/475
    entrypoint:
      - bash
      - -c
      - |
        cp /mongodb-keyfile /etc/mongodb-keyfile
        chmod 400 /etc/mongodb-keyfile
        chown 999:999 /etc/mongodb-keyfile
        exec docker-entrypoint.sh $$@
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}

    deploy:
      labels:
        - 'traefik.enable=false'
      replicas: 1
      placement:
        constraints:
          - node.labels.data2 == true
    networks:
      - overlay_net

  mongo3:
    image: mongo:4.4
    hostname: 'mongo3'
    container_name: 'mongo3'
    restart: unless-stopped
    command: mongod --auth --replSet rs0 --keyFile /etc/mongodb-keyfile
    volumes:
      - '/data/mongo:/data/db'
      - '/mongodb-keyfile:/mongodb-keyfile'
    # https://github.com/docker-library/mongo/issues/475
    entrypoint:
      - bash
      - -c
      - |
        cp /mongodb-keyfile /etc/mongodb-keyfile
        chmod 400 /etc/mongodb-keyfile
        chown 999:999 /etc/mongodb-keyfile
        exec docker-entrypoint.sh $$@
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
    deploy:
      labels:
        - 'traefik.enable=false'
      replicas: 1
      placement:
        constraints:
          - node.labels.data3 == true
    networks:
      - overlay_net

  mongo4:
    image: mongo:4.4
    hostname: 'mongo4'
    container_name: 'mongo4'
    restart: unless-stopped
    command: mongod --auth --replSet rs0 --keyFile /etc/mongodb-keyfile
    volumes:
      - '/data/mongo:/data/db'
      - '/mongodb-keyfile:/mongodb-keyfile'
    # https://github.com/docker-library/mongo/issues/475
    entrypoint:
      - bash
      - -c
      - |
        cp /mongodb-keyfile /etc/mongodb-keyfile
        chmod 400 /etc/mongodb-keyfile
        chown 999:999 /etc/mongodb-keyfile
        exec docker-entrypoint.sh $$@
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
    deploy:
      labels:
        - 'traefik.enable=false'
      replicas: 1
      placement:
        constraints:
          - node.labels.data3 == true
    networks:
      - overlay_net

  mongo5:
    image: mongo:4.4
    hostname: 'mongo5'
    container_name: 'mongo5'
    restart: unless-stopped
    command: mongod --auth --replSet rs0 --keyFile /etc/mongodb-keyfile
    volumes:
      - '/data/mongo:/data/db'
      - '/mongodb-keyfile:/mongodb-keyfile'
    # https://github.com/docker-library/mongo/issues/475
    entrypoint:
      - bash
      - -c
      - |
        cp /mongodb-keyfile /etc/mongodb-keyfile
        chmod 400 /etc/mongodb-keyfile
        chown 999:999 /etc/mongodb-keyfile
        exec docker-entrypoint.sh $$@
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}
    deploy:
      labels:
        - 'traefik.enable=false'
      replicas: 1
      placement:
        constraints:
          - node.labels.data3 == true
    networks:
      - overlay_net

  mongo-on-update:
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongo4
      - mongo5
    environment:
      - REPLICAS=5
