name: Run Workflow Trigger
description: Triggers a workflow using gh CLI
inputs:
  workflow:
    required: true
  args:
    required: true
  token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger workflow
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        WORKFLOW: ${{ inputs.workflow }}
        WORKFLOW_ARGS: ${{ inputs.args }}
        REF: ${{ github.ref }}
      run: bash ./.github/actions/run-workflow/run.sh

