# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
---
- hosts: docker-manager-first
  become: yes
  become_method: sudo
  tasks:
    - name: 'Allow secure docker swarm node communication (managers only)'
      ufw:
        rule: allow
        port: 2377
        proto: tcp
      tags:
        - swarm
        - docker

    - name: 'Create primary swarm manager'
      shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: "docker_info.stdout.find('Swarm: inactive') != -1"
      tags:
        - swarm
        - docker

    - name: 'Get docker swarm manager token'
      shell: docker swarm join-token -q manager
      register: manager_token
      tags:
        - swarm
        - docker

    - name: 'Get docker swarm worker token'
      shell: docker swarm join-token -q worker
      register: worker_token
      tags:
        - swarm
        - docker

  
- hosts: docker-workers
  become: yes
  become_method: sudo
  vars:
    manager_hostname: "{{ groups['docker-manager-first'][0] }}"
  tasks:
    - name: Check if the node is already part of any swarm
      shell: docker info --format "{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}"
      register: worker_swarm_status
      changed_when: false
      tags:
        - swarm
        - docker

    - name: 'Join as a worker'
      shell: "docker swarm join --token {{ hostvars[manager_hostname]['worker_token']['stdout'] }} {{ hostvars[manager_hostname]['ansible_default_ipv4']['address'] }}:2377"
      when: "docker_info.stdout.find('Swarm: inactive') != -1"
      retries: 3
      delay: 20
      tags:
        - swarm
        - docker

- hosts: docker-manager-first
  become: yes
  become_method: sudo
  tasks:
    - name: Label nodes
      shell: docker node update --label-add {{ hostvars[hostname]['data_label'] }}=true {{ hostname }}
      loop: "{{ groups['docker-manager-first'] + groups['docker-workers'] }}"
      loop_control:
        loop_var: hostname
      when: hostvars[hostname]['data_label'] is defined
      tags:
        - swarm
        - docker