name: Check backup(production)
run-name: Checking if a production backup exists ${{ github.event.inputs.backup-label }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to check backup
        required: true
        default: 'production'
        options:
          - production
      branch_name:
        description: Branch to run workflow from
        default: develop
        required: true
      backup-label:
        description: Your Backup label
        required: true
jobs:
  check-backup:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: '${{ github.event.inputs.branch_name }}'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Check backups in ${{ github.event.inputs.environment }}
        id: backup-check
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.BACKUP_HOST }}
          REMOTE_DIR: ${{ vars.BACKUP_DIRECTORY }}
          LABEL: ${{ github.event.inputs.backup-label }}
        run: |
          yarn backup:check