name: Reset data on municipalities
run-name: Reset data on ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to reset
        required: true
        default: 'development'
        options:
          - staging
          - qa
          - development
jobs:
  reset-data:
    name: 'Reset data'
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Clone country config resource package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: './${{ github.event.repository.name }}'

      - name: Read known hosts
        run: |
          cd ${{ github.event.repository.name }}
          echo "KNOWN_HOSTS<<EOF" >> $GITHUB_ENV
          sed -i -e '$a\' ./infrastructure/.known-hosts
          cat ./infrastructure/.known-hosts >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ env.KNOWN_HOSTS }}

      - name: Reset data
        env:
          HOST: ${{ vars.DOMAIN }}
          ENV: ${{ vars.ENVIRONMENT_TYPE }}
          REPLICAS: 1
          MONGODB_ADMIN_USER: ${{ secrets.MONGODB_ADMIN_USER }}
          MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}
          ELASTICSEARCH_SUPERUSER_PASSWORD: ${{ secrets.ELASTICSEARCH_SUPERUSER_PASSWORD }}
          SSH_USER: ${{ vars.SSH_USER }}
        run: |
          cd ${{ github.event.repository.name }}
          bash reset-data.sh
