name: Deploy & run E2E
run-name: Deploy & E2E, triggered by ${{ github.event.client_payload.actor || github.actor }} to ${{ github.event.inputs.environment || 'development' }}
on:
  repository_dispatch:
    types: [run_e2e]
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        required: true
        default: 'development'
        options:
          - development
      core-image-tag:
        description: Core DockerHub image tag
        required: true
        default: 'v1.4.1'
      countryconfig-image-tag:
        description: Your Country Config DockerHub image tag
        required: true
        default: 'v1.4.1'

concurrency:
  group: ci-build
  cancel-in-progress: false

jobs:
  get-core-commit:
    name: Resolve latest core tag
    runs-on: ubuntu-latest
    outputs:
      latest_commit_sha: ${{ steps.get_latest_commit.outputs.commit_sha }}
    steps:
      - name: Checkout opencrvs-core repository
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
        uses: actions/checkout@v3
        with:
          repository: 'opencrvs/opencrvs-core'
          ref: 'develop'
      - name: Get latest commit SHA
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
        id: get_latest_commit
        run: echo "commit_sha=$(git rev-parse HEAD | cut -c 1-7)" >> $GITHUB_OUTPUT

  get-country-config-commit:
    name: Resolve latest Farajaland tag
    runs-on: ubuntu-latest
    needs: get-core-commit
    outputs:
      short_sha: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
      - name: Get short commit hash
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        if: github.event_name == 'push' || github.event_name == 'repository_dispatch'

  deploy:
    needs: [get-country-config-commit, get-core-commit]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'development' }}
      core-image-tag: ${{ github.event.inputs.core-image-tag || needs.get-core-commit.outputs.latest_commit_sha }}
      countryconfig-image-tag: ${{ github.event.inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha }}
      reset: 'true'
    secrets: inherit

  discover-tests:
    name: Discover test directories
    runs-on: ubuntu-22.04
    needs: [get-core-commit, get-country-config-commit]
    outputs:
      test_matrix: ${{ steps.list-tests.outputs.test_matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List Test Directories
        id: list-tests
        run: |
          tests_suites=$(find e2e/testcases -type f -name "*.spec.ts" | jq -R -s -c 'split("\n")[:-1]')
          echo "Test suites: $tests_suites"
          echo "test_matrix=$tests_suites" >> $GITHUB_OUTPUT
          echo "test_matrix=$tests_suites"
      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn/v6
          key: ${{github.event.inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha}}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn
  test:
    needs: [deploy, discover-tests, get-core-commit, get-country-config-commit]
    runs-on: ubuntu-22.04
    environment: ${{ github.event.inputs.environment || 'development' }}
    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.discover-tests.outputs.test_matrix) }}
    name: ${{ matrix.test_file }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn/v6
          key: ${{github.event.inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha}}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test ./${{ matrix.test_file }}
        env:
          DOMAIN: '${{ vars.DOMAIN }}'

      - id: ctrf_check
        if: always()
        run: |
          [ -d ctrf ] && \
            echo "ctrf=true" >> $GITHUB_OUTPUT || \
            echo "ctrf=false" >> $GITHUB_OUTPUT
      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json
        if: always() && steps.ctrf_check.outputs.ctrf == 'true'

      - name: Form the artifact name from test_file
        id: artifact
        run: echo "artifact=$(basename $(dirname ${{ matrix.test_file }}))_$(basename ${{ matrix.test_file }})" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{github.event.inputs.core-image-tag || needs.get-core-commit.outputs.latest_commit_sha}}-${{github.event.inputs.countryconfig-image-tag || needs.get-country-config-commit.outputs.short_sha}}-${{ steps.artifact.outputs.artifact }}
          path: playwright-report/
          retention-days: 30

  get-previous-run:
    runs-on: ubuntu-latest
    outputs:
      previous_run_result: ${{ steps.set-output.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous Run Conclusion
        id: get-previous-conclusion
        run: |
          previous_conclusion=$(gh run list --limit 1 --status=completed --workflow="Deploy & run E2E" --json conclusion -q '.[0].conclusion')
          echo "PREVIOUS_CONCLUSION=$previous_conclusion" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set Output Based on Conclusion
        id: set-output
        run: |
          echo "result=$PREVIOUS_CONCLUSION" >> $GITHUB_OUTPUT

  notify-slack:
    name: Notify Slack on Failure
    runs-on: ubuntu-latest
    needs: [deploy, discover-tests, test, get-previous-run]
    if: failure()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C02LU432JGK'
          slack-message: "❌ E2E pipeline triggered by ${{ github.event.client_payload.actor || github.actor }}'s commit failed. Check the logs at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  notify-slack-success:
    name: Notify Slack on success
    runs-on: ubuntu-latest
    needs: [deploy, discover-tests, test, get-previous-run]
    if: success()
    steps:
      - name: Send Slack notification
        if: needs.get-previous-run.outputs.previous_run_result == 'failure'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C02LU432JGK'
          slack-message: "✅ E2E pipeline triggered by ${{ github.event.client_payload.actor || github.actor }}'s fixed the failing tests 🤩!. Check the logs at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
