name: X - Deploy (development)
run-name: Deploy to ${{ inputs.environment }} with reset=${{ inputs.reset }} core=${{ inputs.core-image-tag }} country config=${{ inputs.countryconfig-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      core-image-tag:
        type: string
        description: Core DockerHub image tag
        required: true
        default: 'v1.4.1'
      countryconfig-image-tag:
        type: string
        description: Your Country Config DockerHub image tag
        required: true
      reset:
        type: string
        description: Reset the environment
        default: 'false'
        required: false
      debug:
        type: boolean
        description: Open SSH session to the runner after deployment
        default: false
        required: false
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy to
        required: true
        default: 'staging'
        options:
          - staging
          - qa
          - development
          - e2e
          - v17
          - v19
      core-image-tag:
        description: Core DockerHub image tag
        required: true
        default: 'v1.7.0'
      countryconfig-image-tag:
        description: Your Country Config DockerHub image tag
        required: true
      reset:
        type: boolean
        description: Reset the environment
        default: false
jobs:
  test:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
        - name: Test variables
          run: |
            echo "sleeping for 2 minutes"
            sleep 120
            echo "environment: ${{ inputs.environment }}"
            echo "core tag: ${{ inputs.core-image-tag }}"
            echo "country tag: ${{ inputs.countryconfig-image-tag }}"
            echo "CUSTOM BRANCH: ${{ github.ref_name }}"
