name: X - Create Hetzner Server
run-name: Create server for ${{ inputs.environment }} environment
on:
    workflow_dispatch:
      inputs:
        environment:
          description: "Short server name (3–5 letters)"
          required: true
    workflow_call:
      inputs:
        environment:
          type: string
          description: Environment to deploy to
          required: true
jobs:
  test:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
        - name: Test variables
          run: |
            echo "env_name: ${{ inputs.environment }}"
            echo ${{ secrets.SMTP_HOST }}
            echo ${{ secrets.SUPER_USER_PASSWORD }}
            echo ${{ vars.ACTIVATE_USERS }}
