name: X - Seed data
run-name: Seed data to ${{ inputs.environment }} core=${{ inputs.core-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      core-image-tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'development'
        options:
          - development
          - qa
          - staging
          - production
          - e2e
          - v17
      core-image-tag:
        description: Core image tag
        required: true
jobs:
  test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    steps:
        - name: Test variables
          run: |
            echo "environment: ${{ inputs.environment }}"
            echo "core tag: ${{ inputs.core-image-tag }}"
            echo ${{ secrets.SUPER_USER_PASSWORD }}
            echo ${{ vars.ACTIVATE_USERS }}
            echo "CUSTOM BRANCH: ${{ github.ref_name }}"