name: Publish release

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch to build from
        default: develop
        required: true
      release_version:
        description: Release version number
        required: true

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: euanmillar,rikukissa
          minimum-approvals: 1
          issue-title: "Release: ${{ github.event.inputs.release_version }}"
          issue-body: "Please approve or deny the publishing of release: ${{ github.event.inputs.release_version }} to Dockerhub"
          exclude-workflow-initiator-as-approver: false
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: '${{ github.event.inputs.branch_name }}'
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push image
        env:
          DOCKERHUB_ACCOUNT: ${{ secrets.DOCKERHUB_ACCOUNT }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          export COUNTRY_CONFIG_VERSION=${{ github.event.inputs.release_version }}
          echo "Publishing a Docker image with a tag $COUNTRY_CONFIG_VERSION"
          bash build-and-push.sh && unset COUNTRY_CONFIG_VERSION
