name: Seed data
run-name: Seed data to ${{ inputs.environment }} core=${{ inputs.core-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      core-image-tag:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'development'
        options:
          - development
          - qa
          - staging
          - production
          - e2e
      core-image-tag:
        description: Core DockerHub image tag
jobs:
  seed-data:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    container: 
      image: ghcr.io/opencrvs/ocrvs-data-seeder:${{ inputs.core-image-tag }}
    outputs:
      outcome: ${{ steps.seed.outcome }}
    timeout-minutes: 60
    steps:
      - name: Seed data on given environment
        uses: nick-fields/retry@v3
        id: seed
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            yarn seed:prod
        env:
          ACTIVATE_USERS: ${{ vars.ACTIVATE_USERS }}
          GATEWAY_HOST: ${{ vars.GATEWAY_HOST }}
          AUTH_HOST: ${{ vars.AUTH_HOST }}
          COUNTRY_CONFIG_HOST: ${{ vars.COUNTRY_CONFIG_HOST }}
          SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
     